### PR TITLE
add javascript to hide alert message after 5 sec

### PR DESCRIPTION
**Pull request by ZmagoD**
https://www.pivotaltracker.com/story/show/114547539

Don't know why is failing in cucumber ?!?

### CODE REVIEW

**Comment by ZmagoD** [comment]
Hi @tochman do you have any idea why 
Given (/^I wait for (\d+) seconds?$/) do |seconds|
  sleep seconds.to_i
end 
don't work ...

**Comment by tochman** [comment]
@ZmagoD What error are you getting?

**Comment by ZmagoD** [comment]
the cucumber scenario don't pass 
  Scenario: Delete user
     And I click on "Destroy" for "Ivan"
     Then I should see "User was successfully destroyed"
     And I wait for 6 seconds
    Then I should not see "User was successfully destroyed"
     And I should see 3 instances of User

**Comment by tochman** [comment]
Yes, but what error is it returning? perhaps you should use the `@javascript` hook?

**Comment by fighterii** [comment]
From The Semaphore Details Log:

```Scenario: Delete user                                     # features/godmin/users.feature:51
    And I click on "Destroy" for "Ivan"                     # features/step_definitions/godmin_steps.rb:57
    Then I should see "User was successfully destroyed"     # features/step_definitions/godmin_steps.rb:41
    And I wait for 6 seconds                                # features/step_definitions/godmin_steps.rb:104
    Then I should not see "User was successfully destroyed" # features/step_definitions/godmin_steps.rb:45
      expected not to find text "User was successfully destroyed" in "Toggle navigation Project Unify Users Skills Sign out User was successfully destroyed User User Name Skill List Clear filter Select all Deselect all Destroy Create User User name Mentor Private Skill list Thomas Show Edit Destroy Mazen Show Edit Destroy Tarek Show Edit Destroy Anders Show Edit Destroy Showing 4 out of 4 user Some info About Project Unify Some more info Address info? Developed with by volunteers from AgileVentures Sponsored by CraftAcademy and Pinyata" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/godmin_steps.rb:46:in `/^I should not see "([^"]*)"$/'
      features/godmin/users.feature:55:in `Then I should not see "User was successfully destroyed"'
    And I should see 3 instances of User                    # features/step_definitions/godmin_steps.rb:53```

**Comment by ZmagoD** [comment]
@tochman yes was that thank you!

**Comment by tochman** [comment]
ready to go @ZmagoD ?

**Pull request merged**
