### PR TITLE
Get rid of Geocoding OverQueryLimitError

### PR DESCRIPTION
**Pull request by fighterii**
PT: https://www.pivotaltracker.com/story/show/126850609

this solution makes the `OverQueryLimitErrors` coming from `Geocoder` disappear.

This is achieved by using a Cache for the requests via a Redis server.

This adds the `redis` gem as a new dependency and also you have to start the redis server manually 
(on c9 e.g. `sudo service redis-server start`)

Using Redis is the recommended way by [Geocoder](http://www.rubydoc.info/gems/rails-geocoder/0.9.11#Caching_Results). However, we might just implement the other mentioned method by using a simple RubyHash, if we want to avoid to add another dependency to the project.

### CODE REVIEW

**Comment by tochman** [comment]
ready to merge?

**Comment by fighterii** [comment]
Maybe we have to Install the Redis To Go add-on on Heroku: `heroku addons:add redistogo` if we want to use this

?

**Comment by fighterii** [comment]
To automatically start Redis server (and Postgres) on C9:

change directory to `~` (propably just `cd ..`)
`nano .profile` (Note: `.profile` won't be read if there is a `.bash_profile` or `.bash_login` file - which isn't the case on C9, but if you want to try it on your local machine this could be)

add the following lines
`sudo service postgresql start`
`sudo service redis-server start`

Exit & Save

Now every time you open the bash terminal, it will start both servers.
@tochman @diraulo

**Comment by diraulo** [comment]
@fighterii @tochman 
Redis is already installed and running on SemaphoreCI so it shouldn't be a hassle to plug that in for tests there.

more info about the port it's running on [here](https://semaphoreci.com/docs/databases/redis.html)

**Comment by fighterii** [comment]
Sorry - i definitley still have some problems with using git -.-

**Comment by fighterii** [comment]
Sorry - i fucked this one up completely. better to make a new PR.

**Pull request closed without merging**
