### PR TITLE
Devise api

### PR DESCRIPTION
**Pull request by tochman**
**PT Stories:**
[Add user authentication endpoint to API](https://www.pivotaltracker.com/story/show/113903759)
[Add tagging endpoint to API](https://www.pivotaltracker.com/story/show/113903937)
[Refactor api scenarios/specs](https://www.pivotaltracker.com/story/show/114473947)
- Moved away from Cucumber tests for API
- Adds `Api::V1::RegistrationsController`
- Adds `Api::V1::SessionsController` 
- Adds `#skills` action to `api/v1/users_controller` to update `skill_list`
### User registration

```
curl -H "Content-Type: application/json" -d '{"user":{"email":"thomas@craftacademy.se","password":"password", "password_confirmation":"password"}}' -X POST http://localhost:3000/api/v1/users
```

response;

```
{"message":"success","user":{"id":41,"user_name":"Thomas Ochman","token":"ynvaUPDxMXfKrHcw164f"}}
```
### User sign in

```
curl -H "Content-Type: application/json" -X POST -d '{"user":{"user_name":"Thomas Ochman","password":"password", "email":"thomas@craftacademy.se"}}' http://localhost:3000/api/v1/users/sign_in
```

response:

```
{"id":41,"user_name":"Thomas Ochman","created_at":"2016-03-04T11:18:49.808Z","updated_at":"2016-03-04T11:19:25.268Z","email":"thomas@craftacademy.se","mentor":false,"private":false,"authentication_token":"ynvaUPDxMXfKrHcw164f"}
```
### 

Doing a GET request (to the users endpoint) will require two headers `X-User-Email:` and `X-User-Token:` and look like this:

```
curl GET http://localhost:3000/api/v1/users --header "X-User-Email: thomas@craftacademy.se" --header "X-User-Token: xxxxxxxx"
```

If you try to access the endpoint without a token, the response would be:

```
http://localhost:3000/api/v1/users
{"error":"You need to sign in or sign up before continuing."}
```

And, of course it you provide wrong credentials you'll be notified. For example:

```
{"errors":{"email":["is invalid"]}}
```

You can also pass in the token and email as part of the url when using a GET request to the endpoint

```
http://localhost:3000/api/v1/users?user_email=thomas@craftacademy.se&user_token=xxxxxxxx
```

### CODE REVIEW

**Comment by ZmagoD** [comment]
Hi @tochman can we pair on that if you have some time?

**Comment by tochman** [comment]
Sure @ZmagoD I'll be around tomorrow morning.

**Comment by ZmagoD** [comment]
for me is OK tomorrow morning.

**Comment by tochman** [comment]
Some parts of this PR will need to be revisited but I'm merging this in. Please create tickets if further code review reveals some shortcomings, improvements or bugs.

**Pull request merged**
