### PR TITLE
implemented friendly-ids gem

### PR DESCRIPTION
**Pull request by ivan-sathianathan**
I have implemented the "friendly-id" gem, including one basic feature test and a few basic unit tests. I hope this coverage is enough but please let me know if anything else should be covered.

https://www.pivotaltracker.com/story/show/114039959

### CODE REVIEW

**Comment by tochman** [comment]
Looks good. We should also update the api and godmin controllers get User methods to use `:slug` rather then id. Also, the response from `api/v1/users` should include the url with slug.

**Comment by tochman** [comment]
@ivan-sathianathan Will you have time to work on this PR?

**Comment by ivan-sathianathan** [comment]
Hi Thomas,

I won't have time to work on this story I'm afraid, I've recently started a
new job. Apologies.

Ivan

**Comment by tochman** [comment]
No problems @ivan-sathianathan Congratulations on the new job! :-)

**Comment by tochman** [comment]
Closing this. Continued on https://github.com/AgileVentures/project_unify/pull/49

**Pull request closed without merging**
