### PR TITLE
115542093 add ip to geocode

### PR DESCRIPTION
**Pull request by ZmagoD**
@tochman don't merge! I need to write some tests first and fix a VCR cassette
https://www.pivotaltracker.com/story/show/115542093

### CODE REVIEW

**Comment by tochman** [comment]
Cab you walk me through the process? How will the geocoding be performed?

**Comment by ZmagoD** [comment]
In the registration_controler  cheate checks in the user send the lat, long 
 def create
    self.resource = build_resource(sign_up_params.merge params['user'])
    resource.ip_address = request.remote_ip if resource.latitude.blank? || resource.longitude.blank?
    resource.save
    yield resource if block_given?
    if resource.persisted? .....

than in the User model I add a check if lat, long present then geocode by lat long hmm .. i shoud put and in that :)
  after_validation :reverse_geocode, if: lambda{ |obj| obj.latitude.present? || obj.longitude.present? }
  after_validation :geocode, if: lambda{ |obj| obj.ip_address.present? }

and if ip address present geocode by that. And this methods puts, the geocode results in the user table

  reverse_geocoded_by :latitude, :longitude, address: :location do |obj,results|
    if geo = results.first
      obj.city     = geo.city
      obj.state    = geo.state
      obj.country  = geo.country
    end
  end

  geocoded_by :ip_address do |obj,results|
    if geo = results.first
      obj.city     = geo.city
      obj.state    = geo.state
      obj.country  = geo.country
    end
  end

**Comment by tochman** [comment]
Okay @ZmagoD So the ip geocoding is performed only as the last resort? Good job.

**Comment by ZmagoD** [comment]
@tochman can you double check using postman. I can't get the thing work with postman

**Comment by ZmagoD** [comment]
this is the log from the server 
Started POST "/api/v1/users" for 193.77.54.115 at 2016-03-18 08:17:40 +0000
Cannot render console from 193.77.54.115! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Error occurred while parsing request parameters.
Contents:

{user:{user_name: 'Thomastest',email: 'test@craft.com', gender: 'Male',password: 'password',password_confirmation: 'password'}}

ActionDispatch::ParamsParser::ParseError (822: unexpected token at '{user:{user_name: 'Thomastest',email: 'test@craft.com', gender: 'Male',password: 'password',password_confirmation: 'password'}}'):
  actionpack (4.2.5.2) lib/action_dispatch/middleware/params_parser.rb:53:in `rescue in parse_formatted_parameters'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/params_parser.rb:32:in`parse_formatted_parameters'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/params_parser.rb:23:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in`call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in`call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.2) lib/active_record/query_cache.rb:36:in`call'
  activerecord (4.2.5.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.2) lib/active_record/migration.rb:377:in`call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in`**run_callbacks**'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/reloader.rb:73:in`call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in`call'
  web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in`catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
  railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in`call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in`call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in`call'
  railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.2) lib/rails/application.rb:165:in`call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in`call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in`service'
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in`block in start_thread'

  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.9ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (99.3ms)

**Comment by tochman** [comment]
What test are you running?

**Comment by ZmagoD** [comment]
postman

**Comment by ZmagoD** [comment]
The specs in api/registration_spec are passing so maybe I'm doing something wrong with postman

**Comment by tochman** [comment]
I've never got it to work on Postman :-(

**Comment by ZmagoD** [comment]
: ) maybe is here the the problem 
Started POST "/api/v1/users" for 193.77.54.115 at 2016-03-18 08:17:40 +0000
Cannot render console from 193.77.54.115! **Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255**
Error occurred while parsing request parameters.
Contents:

**Comment by tochman** [comment]
Perhaps. You can research this if you want but since the test are passing and I can make calls from the mobile app I think we can prioritize other tasks ;-)

**Comment by ZmagoD** [comment]
Ok :)

**Comment by tochman** [comment]
Ready to merge @ZmagoD ?

**Comment by tochman** [comment]
@ZmagoD  Came to think of a potential need for refactoring or perhaps a bug. How is the `ip_address` set? The way I see it, that attribute will be `nil` no matter what. (In your tests you set it manually) Shouldn't we use the `last_sign_in_ip` ?

**Comment by ZmagoD** [comment]
@tochman hmm.. 
here is my create method in the registration_controler and it should get the ip of the user request..
  def create
    self.resource = build_resource(sign_up_params.merge params['user'])
    **resource.ip_address = request.remote_ip if resource.latitude.blank? || resource.longitude.blank?**
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        sign_up(resource_name, resource)
        @resource = resource
        render 'api/v1/users/success'
      else
        expire_data_after_sign_in!
        respond_with resource #, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

maybe it will be better to put in the session_controller so that every time session is create the ip field is set if there are no lat and lng already in the database. If I understand it. Yes in the tests I only test it on the model level.... my fault

**Pull request merged**
