### PR TITLE
#113903741 add devise to api namespace [WIP]

### PR DESCRIPTION
**Pull request by ZmagoD**
https://www.pivotaltracker.com/story/show/113903741

### CODE REVIEW

**Comment by tochman** [comment]
You have to update the cucumber scenarios for creating users.

```
Email can't be blank
```

**Comment by ZmagoD** [comment]
@tochman yes I know and we have to add fields for user creation in godmin

**Comment by tochman** [comment]
Do you need help on this?

**Comment by ZmagoD** [comment]
If you could stretch a day to 32 hours :) Actualy it will be nice to have some help.

**Comment by tochman** [comment]
@ZmagoD @sampritipanda did you guys have had a chance to discuss this? I'd love to merge this in ASAP

**Comment by sampritipanda** [comment]
Closed in favor of #21

**Pull request closed without merging**
