### PR TITLE
Coverall cleanup

### PR DESCRIPTION
**Pull request by fighterii**
Made a bit of clean-up, outsourced the starting and options of the SimpleCov into a .simplecov file, and specified command names for Cucumber + RSpec

### CODE REVIEW

**Comment by fighterii** [comment]
Okay, now no comments are posted from coveralls.io

**Comment by fighterii** [comment]
according to https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails maybe this has to be done:

Unless you've added coveralls:push to your default rake task, your build command will need to be updated on your CI to reflect this, ex:

bundle exec rake :test_with_coveralls

**Comment by tochman** [comment]
So, do you want me to merge this in and update the command on Semaphore to `bundle exec rake :test_with_coveralls`?

**Comment by fighterii** [comment]
I think this will do it, because if i execute the same command locally, both (cucumber and rspec) tests are run and Coverall is called and tries to push it to coverall.io (but doesn't because it is not in CI enviroment)

So i assume, that if the tests are called with this command on semaphore the merged results were pushed to coverall.io correctly

**Comment by tochman** [comment]
Okay, let's try that

**Pull request merged**
