### PR TITLE
Friendlyids

### PR DESCRIPTION
**Pull request by ZmagoD**
implemented friendly-ids gem #26

https://www.pivotaltracker.com/n/projects/1525675/stories/114039959

### CODE REVIEW

**Comment by ZmagoD** [comment]
@tochman what is to do here? 
the thing is working in admin panel...

**Comment by tochman** [comment]
Not much I think unless we want to add the slugs to the API endpoints. Fix the conflicts.

**Comment by ZmagoD** [comment]
Then this is it....

**Comment by tochman** [comment]
I'm going to merge this in now. ;-)

**Pull request merged**
