### PR TITLE
114519425 add geo attributes to user [RFC]

### PR DESCRIPTION
**Pull request by ZmagoD**
https://www.pivotaltracker.com/story/show/114519425

### CODE REVIEW

**Comment by ZmagoD** [comment]
@tochman here will be nice to have VCR set up to stub the geocoder calls and get rid of these log when running rspec: "Google Geocoding API error: over query limit."

**Comment by tochman** [comment]
True, would you like to add that as part of this PR @ZmagoD ?

**Comment by ZmagoD** [comment]
Yes

**Comment by tochman** [comment]
We also need to return those attributes in the api call @ZmagoD

**Comment by tochman** [comment]
Fantastic. A little worried about all these `yml` files but they might prove useful. Merging this in. Good job @ZmagoD !

**Pull request merged**
