### PR TITLE
#114553545 Merging Coverall Test Results

### PR DESCRIPTION
**Pull request by fighterii**
https://www.pivotaltracker.com/story/show/114553545

Rakefile task added, .simplecov for options added, modified env.rb and rails_helper.rb

By modifiying the .simplecov file with additional "add_filter" methods we can specify which files should not be tested (regarding to the second point of the story, that we only want to test files within the app folder)

### CODE REVIEW

**Comment by fighterii** [comment]
@tochman : When you want to merge this in, you have to change the Semaphore task to:
`bundle exec rake test_with_coveralls`

(in contrast to the failing `bundle exec rake :test_with_coveralls` with a doublepoint, from [PR#44](https://github.com/AgileVentures/project_unify/pull/44))

**Comment by fighterii** [comment]
However, i noticed a significant drop in coverage.

bad_coverage_report

example_file_uncovered_lines
Because the blank lines and "end" lines are counted as relevant lines.

This is an issue of SimpleCov [Issue #444](https://github.com/colszowka/simplecov/issues/444)

I tried the suggested fix with changing line 7 of the merge_helpers.rb of the SimpleCov lib locally and got the following improvements:

coverage_with_fix

As you can see, unrelevant lines are now correctly displayed in grey and not counted as uncovered:
example_file_with_fix

**Comment by tochman** [comment]
Hmm.. I see. Weird. Are the cucumber tests taken into consideration in the above coverage calculations?

**Comment by fighterii** [comment]
Let me check this again..

**Comment by fighterii** [comment]
Weird. It seems like this are only the cucumber scores.

I tested this behavior by changing the test_with_coverall task

For `task :test_with_coveralls => [:spec, :cucumber, 'coveralls:push']` i get the scores from above (58.95%)

For only rspec (`task :test_with_coveralls => [:spec,  'coveralls:push']`) i get 0.0% coverage.

For only cucumber (`task :test_with_coveralls => [:cucumber,  'coveralls:push']`) i get the scores as in the combined tests (58.95%)

**Comment by fighterii** [comment]
@tochman : Seems its working (at least locally) now.
I get test coverage of ~90%.

Maybe we could test this within the CI now by changing the Semaphore task to:
`bundle exec rake test_with_coveralls`

The problem was, that SimpleCov needs to know which spec files belong to which "group" of testing.
So we have to add `SimpleCov.command_name 'test:xyz'` to ONE file of each Rspec folder. 
I chosed the two `user_spec.rb` in `models` and `requests\api\v1`

**Comment by tochman** [comment]
I'll merge this in if you feel it's ready to be tested on semaphore.

**Comment by fighterii** [comment]
I think this should work now :)

**Pull request merged**
