### PR TITLE
users became friends v2

### PR DESCRIPTION
**Pull request by ZmagoD**

### CODE REVIEW

**Comment by ZmagoD** [comment]
When I compare the branches the git don't recognise the changes wtf...

**Comment by ZmagoD** [comment]
@tochman the commits I made exist on the develop branch look here https://github.com/AgileVentures/project_unify/commits/develop?page=2

**Comment by ZmagoD** [comment]
@tochman this
Merge pull request #41 from tochman/mailboxer 
deletes my code 
https://github.com/AgileVentures/project_unify/commit/8fa18a21317d507c36684c59b65f163402f38e02

**Comment by tochman** [comment]
What a mess. Sorry about this.

**Pull request closed without merging**
