### PR TITLE
#114553545 User introduction

### PR DESCRIPTION
**Pull request by fighterii**
https://www.pivotaltracker.com/story/show/114514673

Introduction field added to User
(Database, Show/Edit User, API JSON responds success/show)

### CODE REVIEW

**Comment by tochman** [comment]
Okay, now I see. You could have kept the old one. It would have been updated with the new commits. But no problem. 

About the `success.json.jbuilder`: Yes, that is used to set values for the current_user in the mobile app so we could make use of `:introduction` there as well.

**Comment by fighterii** [comment]
Okay sorry for messing up the history a bit, just getting to know github better and better each day :)

i'll introduce that as well. I noticed that the gender field isn`t set up within in the success.json.jbuilder, but i think its better to change/add this in a separate PR?

**Comment by tochman** [comment]
No problems @fighterii Good job!

**Comment by tochman** [comment]
As a last thing, after fixing the specs, please update the PR description with  a PT link and what has beed added, etc.

**Comment by tochman** [comment]
Looks good. Let's merge this in. Thank you @fighterii

**Comment by fighterii** [comment]
@tochman i noticed that the changes of introduction disappeared as well (tests & changes to models/views)

**Pull request merged**
