### PR TITLE
Auditing

### PR DESCRIPTION
**Pull request by freeranger**
Added brakeman and bundler-audit
Note that right now they are showing vunerabilities:
Our version of rails is vulnerable to DDOS and there are various issues with some of our gems.
See report here:
https://semaphoreci.com/freeranger/project_unify/branches/auditing/builds/4

### CODE REVIEW

**Comment by tochman** [comment]
@freeranger Looking at the commits it seems that this one builds on https://github.com/AgileVentures/project_unify/pull/3 I have no problem with that atm but please let me know in what order you want me to merge this in. Also, try to always create your feature branches from `develop`rather from another feature branch (that is what happened in this case)

**Comment by freeranger** [comment]
Hi, ok so you mean I branched my devlop branch but I should have branched the main develop branch? Oops!
 Maybe you should merge the other branch in and then I rebase this or something?  Or maybe easier to ditch this and start again?
The bits from this I want are:
lib/tasks/brakeman.rake
lib/tasks/bundle-audit.rake
Rakefile
Gemfile
Gemfile.lock

**Comment by tochman** [comment]
Okay, no need to rebase. Those commits will go away once your first PR is merged in. No drama. ;-)

**Comment by freeranger** [comment]
phew :)

**Pull request merged**
