### PR TITLE
Add CORS to enable mobile app to talk to the api

### PR DESCRIPTION
**Pull request by freeranger**

### CODE REVIEW

**Comment by freeranger** [comment]
Made the updates you suggested.
Testing this would be tricky since it is CORS - we would have to spin the server up, which we do anyway in testing, and then spin up a separate website on another port to make an ajax call to the server.
That's not to say it is impossible to do but am wondering if the effort exceeds the benefit?  
Once we have the mobile app going the it's acceptance tests will have to run against a deployed instance and basically nothing will work if CORS isn't working....

**Comment by freeranger** [comment]
What whitespace do you mean?  Is there a plugin for RubyMine that will show them?  I do this in Visual Studio all the time in my real life with a plugin to show extra spaces in red.
re: origins - yes you can limit where you accept CORS requests from, which we should do - but at the moment we don't know where that would be :)

**Comment by tochman** [comment]
I see a lot of extra line breaks, thats all.

**Comment by tochman** [comment]
re: `origins` - sounds good @freeranger Thanks for the info.

**Pull request merged**
