### PR TITLE
#114603533 Add ability for users to become friends 

### PR DESCRIPTION
**Pull request by ZmagoD**
https://www.pivotaltracker.com/story/show/114603533

### CODE REVIEW

**Comment by ZmagoD** [comment]
I need some help here!
1. what friendship related data will be presented in the user index if any
2. what data will be presented in the user show (friend name, url, created_at,....) and if this data is accessible if the user is not a friend.
3. how to add model related methods like .invite, .approve, .remove_friendship, .... in the json...

**Comment by tochman** [comment]
Hi @ZmagoD 
I'm not sure I understand your question but I assume that you are asking about how the friendship endpoint should be constructed, right? Some thoughts...

### Creating friendships

POST /api/v1/users/friendship/create
params:
current_user_id: mandatory
friend_id: mandatory

```
current_user.invite friend
```

Response should just be a status message (I assume that Amistad does not allow `blocked` users to request friendships, in that case the request would fail, right?)

### Listing requests

When we return the current user we should add pending requests

```
current_user.pending_invited_by
```

### Approving requests

POST /api/v1/users/friendship/respond
I assume that each request has an id and can be either accepted or rejected.

### Pending requests

We can add pending requests to the user endpoint when returning the current user. 

### Returning friendship status

We should also be able to return the current friendship status when returning a user instance (or the user index). Every request has the current users token attached to it (in headers) so we should be able to att that to the json response. That info will be useful in the mobile app.

**Comment by ZmagoD** [comment]
@tochman 

Work done:
in the user show:
  json.friends user.friends do |friend|
    json.id friend.id
    json.name friend.name
    json.url url_for(friend)
  end
  if current_user
    json.pending_friendships user.pending_invited_by do |pending|
      json.id pending.id
      json.name pending.name
      json.url url_for(pending)
    end
  end

I add the friend list and the list of pending invitation

in the user controller I had added 3 methods to add friendship, block friendship and accept friendship.
get 'user/:id/friendship/:friend_id'
get 'user/:id/friendship/:friend_id/confirm'
get 'user/:id/friendship/:friend_id/block'

**Comment by tochman** [comment]
Cool. I'll review this and merge in. If we encounter any issues we deal with it later. Great job. I'm working on the messaging system atm.

**Comment by tochman** [comment]
@ZmagoD I don't know what happened but I can't see this code on develop. Can you investigate?

**Comment by ZmagoD** [comment]
hm strange do I make a new PR

**Comment by tochman** [comment]
Hmm... It is probably my fault. But yes. If you could submit a new PR that would be great @ZmagoD

**Pull request merged**
